name = "aem-productbus-demo-worker"
main = "src/index.js"
account_id = "852dfa4ae1b0d579df29be65b986c101"
workers_dev = true
compatibility_date = "2024-11-11"

[observability]
enabled = true

[vars]
API_ORIGIN = "https://api.adobecommerce.live"
API_ORG = "dylandepass"
API_SITE = "aem-productbus-demo"
ALLOWED_ORIGIN = "*"

# Secret: API_TOKEN (set via `wrangler secret put API_TOKEN`)
